#!/usr/bin/env python3
"""Generate images/README.md from the prompt catalog in generate-showcase.scm.

No network, no GENERATION_LOG.csv — reads the .scm file directly and
checks what PNGs exist on disk. Used by the non-phony Makefile target:

    images/README.md: scripts/generate-showcase.scm
"""

import os
import re
import sys

SCRIPT = os.path.join(os.path.dirname(__file__), "generate-showcase.scm")
IMAGES_DIR = os.path.join(os.path.dirname(__file__), "..", "images")

# Parse (generate N "category" "prompt" "filename" W H)
PATTERN = re.compile(
    r'\(generate\s+(\d+)\s+"([^"]+)"\s+"([^"]+)"\s+"([^"]+)"\s+(\d+)\s+(\d+)\)'
)

CAT_LABELS = {
    "programming": "Scheme / Programming",
    "ai-agent": "AI / Agent",
    "infra": "Architecture / Infrastructure",
    "nature": "Nature / Organic",
    "abstract": "Abstract / Geometric",
    "retro": "Retro / Vintage",
    "minimal": "Minimalist / Icon",
    "scifi": "Sci-fi / Futuristic",
    "art-style": "Art Styles",
    "hero": "Hero / Banner (1024x512)",
}

CAT_ORDER = [
    "programming", "ai-agent", "infra", "nature", "abstract",
    "retro", "minimal", "scifi", "art-style", "hero",
]


def main():
    with open(SCRIPT) as f:
        text = f.read()

    matches = PATTERN.findall(text)
    if not matches:
        print("ERROR: no prompts found in", SCRIPT, file=sys.stderr)
        sys.exit(1)

    # Group by category
    categories = {}
    for seq, cat, prompt, filename, w, h in matches:
        fn = f"{filename}.png"
        path = os.path.join(IMAGES_DIR, fn)
        size = os.path.getsize(path) if os.path.exists(path) else 0
        entry = {
            "seq": int(seq), "prompt": prompt, "filename": fn,
            "w": int(w), "h": int(h), "size": size,
        }
        categories.setdefault(cat, []).append(entry)

    total_size = sum(
        e["size"] for entries in categories.values() for e in entries
    )
    present = sum(
        1 for entries in categories.values()
        for e in entries if e["size"] > 0
    )

    lines = [
        "# Generated Images",
        "",
        "100 images generated by guile-sage via `ollama-generate-image` using",
        "the [x/flux2-klein:4b](https://ollama.com/x/flux2-klein) model on local Ollama.",
        "",
        "## Pipeline",
        "",
        "```",
        "scripts/generate-showcase.scm   # Generate 100 images -> tests/fixtures/showcase/",
        "scripts/promote-images.sh       # Promote to images/ with this README",
        "```",
        "",
        "Makefile targets:",
        "```bash",
        "make generate-showcase   # Run generation (requires Ollama + flux model)",
        "make promote-images      # Copy showcase -> images/ and rebuild this README",
        "```",
        "",
        f"**Total**: {len(matches)} images ({present} present), {total_size // (1024 * 1024)} MB",
        "",
    ]

    for cat in CAT_ORDER:
        entries = categories.get(cat, [])
        if not entries:
            continue
        label = CAT_LABELS.get(cat, cat)
        lines.append(f"## {label}")
        lines.append("")
        lines.append("| # | Image | Size | Prompt |")
        lines.append("|---|-------|------|--------|")
        for e in entries:
            size_kb = e["size"] // 1024
            dim = f'{e["w"]}x{e["h"]}'
            lines.append(
                f'| {e["seq"]} | [{e["filename"]}]({e["filename"]}) ({dim})'
                f' | {size_kb}KB | {e["prompt"]} |'
            )
        lines.append("")

    # Thumbnail sample grid
    samples = [
        ("lambda-neon.png", "Lambda"),
        ("sage-owl.png", "Sage"),
        ("circuit-bonsai.png", "Bonsai"),
        ("cyberpunk-alley.png", "Cyberpunk"),
        ("hero-gradient-wave.png", "Hero"),
    ]
    lines.append("## Thumbnails (sample)")
    lines.append("")
    lines.append("| | | | | |")
    lines.append("|---|---|---|---|---|")
    row = "| " + " | ".join(f"![{label}]({fn})" for fn, label in samples) + " |"
    lines.append(row)
    lines.append("")

    readme_path = os.path.join(IMAGES_DIR, "README.md")
    with open(readme_path, "w") as f:
        f.write("\n".join(lines))

    print(f"Wrote {readme_path} ({len(lines)} lines, {len(matches)} images)")


if __name__ == "__main__":
    main()
