#!/bin/sh
# promote-images.sh --- Copy showcase images to images/ with metadata
#
# Usage: sh scripts/promote-images.sh [image1.png image2.png ...]
#
# If no arguments, promotes ALL showcase images.
# Creates images/README.md with prompt/model metadata from GENERATION_LOG.csv.

set -e

SHOWCASE_DIR="tests/fixtures/showcase"
IMAGES_DIR="images"
LOG_CSV="$SHOWCASE_DIR/GENERATION_LOG.csv"

if [ ! -f "$LOG_CSV" ]; then
    echo "Error: $LOG_CSV not found. Run scripts/generate-showcase.scm first."
    exit 1
fi

mkdir -p "$IMAGES_DIR"

# Determine which files to promote
if [ $# -gt 0 ]; then
    FILES="$@"
else
    FILES=$(ls "$SHOWCASE_DIR"/*.png 2>/dev/null)
fi

COUNT=0
for src in $FILES; do
    fname=$(basename "$src")
    cp "$src" "$IMAGES_DIR/$fname"
    COUNT=$((COUNT + 1))
done

echo "Promoted $COUNT images to $IMAGES_DIR/"

# Generate README with metadata
cat > "$IMAGES_DIR/README.md" << 'HEADER'
# Generated Images

Images generated by guile-sage using Ollama image generation.

## Metadata

| File | Category | Size | Time | Model | Prompt |
|------|----------|------|------|-------|--------|
HEADER

# Parse CSV (skip header), emit markdown table rows
tail -n +2 "$LOG_CSV" | while IFS=',' read -r seq filename width height time_s size_bytes category prompt model host status; do
    if [ "$status" = "ok" ]; then
        # Strip quotes from prompt
        clean_prompt=$(echo "$prompt" | tr -d '"')
        clean_model=$(echo "$model" | tr -d '"')
        size_kb=$((size_bytes / 1024))
        printf "| %s | %s | %sKB | %ss | %s | %s |\n" \
            "$filename" "$category" "$size_kb" "$time_s" "$clean_model" "$clean_prompt" \
            >> "$IMAGES_DIR/README.md"
    fi
done

echo "" >> "$IMAGES_DIR/README.md"
echo "Generated: $(date -u '+%Y-%m-%dT%H:%M:%SZ')" >> "$IMAGES_DIR/README.md"

echo "Wrote $IMAGES_DIR/README.md"
